name: Feature request
description: Suggest a new feature or enhancement for Starlopost
title: "[FEATURE] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

        Please provide a detailed description of the feature you are requesting. Be sure to follow the guidelines in our [Contribution Guide](CONTRIBUTING.md).

  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a short summary of the feature request.
      placeholder: "[FEATURE] Add new functionality"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature.
      placeholder: Describe the feature in detail, including its purpose and how it should work.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed.
      placeholder: Describe the problem this feature would solve and why it's important.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: List any alternative solutions or features you've considered.
      placeholder: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information that might help us understand the feature request.

  - type: checkboxes
    id: agree
    attributes:
      label: Agreement
      description: Please check to confirm you have read the guidelines.
      options:
        - label: I have read the [Contribution Guide](CONTRIBUTING.md)
          required: true
